### ISSUE TITLE
Please update Anydesk to version 6.3.1

### ISSUE THREAD

**Issue by boustanihani** [flathub/com.anydesk.Anydesk#136] opened 2024-03-20 13:58 UTC
Please update to version 6.3.1 (18 Mar 2024)

6.3.0 no longer installs..

Check: https://anydesk.com/en/changelog/linux

**Comment by der-eismann** [comment] 2024-03-20 14:02
Duplicate of #134. Was fixed in #135, unfortunately it seems to take a while to be available.

**Closed by der-eismann** 2024-03-20 14:02 UTC
